=== BigHillSoftware/Fremont/Code/Fremont/Resources/ModelDefinition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Model">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="ModelEnum"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="ModelClass"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="ModelArray"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="ModelDictionary"/>
      </xs:sequence>
      <xs:attribute name="rootDataType" use="required" type="xs:string"/>
      <xs:attribute name="rootXMLName" use="required" type="xs:string"/>
      <xs:attribute name="rootFormatString" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ModelEnum">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="EnumItem"/>
      </xs:sequence>
      <xs:attribute name="enumName" use="required" type="xs:string"/>
      <xs:attribute name="xmlName" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ModelEnumItem">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="value" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ModelClass">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="ModelProperty"/>
      </xs:sequence>
      <xs:attribute name="className" use="required" type="xs:string"/>
      <xs:attribute name="xmlName" use="required" type="xs:string"/>
      <xs:attribute name="textDataType" use="required" type="xs:string"/>
      <xs:attribute name="textPropertyName" use="required" type="xs:string"/>
      <xs:attribute name="textFormatString" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ModelProperty">
    <xs:complexType>
      <xs:attribute name="propertyName" use="required" type="xs:string"/>
      <xs:attribute name="dataType" use="required" type="xs:string"/>
      <xs:attribute name="xmlType" use="required" type="xs:string"/>
      <xs:attribute name="xmlName" use="required" type="xs:string"/>
      <xs:attribute name="formatString" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ModelArray">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="1" ref="ModelArrayElement"/>
      </xs:sequence>
      <xs:attribute name="xmlName" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ModelArrayElement">
    <xs:complexType>
      <xs:attribute name="dataType" use="required" type="xs:string"/>
      <xs:attribute name="xmlName" use="required" type="xs:string"/>
      <xs:attribute name="formatString" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ModelDictionary">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="ModelDictionaryElement"/>
      </xs:sequence>
      <xs:attribute name="xmlName" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ModelDictionaryElement">
    <xs:complexType>
      <xs:attribute name="dataType" use="required" type="xs:string"/>
      <xs:attribute name="xmlName" use="required" type="xs:string"/>
      <xs:attribute name="key" use="required" type="xs:string"/>
      <xs:attribute name="formatString" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== BigHillSoftware/Fremont/Code/Fremont_Sample/XML/ModelDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<Model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ModelDefinition.xsd"
 rootDataType="UDC"
 rootXMLName="Company"
 rootFormatString="">
    
	<ModelEnum enumName="CompensationTerm" xmlName="CompensationTerm">
        <ModelEnumItem name="PERHOUR" value="0"/>
        <ModelEnumItem name="PERMONTH" value="1"/>
        <ModelEnumItem name="PERYEAR" value="2"/>
    </ModelEnum>

    <ModelClass className="Company" xmlName="Company" textPropertyName="description" textDataType="STRING" textFormatString="">
		<ModelProperty propertyName="name" dataType="STRING" xmlType="ATTRIBUTE" xmlName="name" formatString=""/>
        <ModelProperty propertyName="dateFounded" dataType="DATE" xmlType="ATTRIBUTE" xmlName="dateFounded" 
			formatString="EEE MMM dd HH:mm:ss zzz yyyy"/>
		<ModelProperty propertyName="location" dataType="STRING" xmlType="ELEMENT" xmlName="Location" formatString=""/>
        <ModelProperty propertyName="computers" dataType="DICTIONARY" xmlType="ELEMENT" xmlName="Computers" formatString=""/>
        <ModelProperty propertyName="employees" dataType="ARRAY" xmlType="ELEMENT" xmlName="Employees" formatString=""/>
        <ModelProperty propertyName="logoImageData" dataType="DATA" xmlType="ELEMENT" xmlName="LogoImageData" formatString=""/>
    </ModelClass>

    <ModelClass className="Employee" xmlName="Employee" textPropertyName="" textDataType="" textFormatString="">
        <ModelProperty propertyName="name" dataType="STRING" xmlType="ATTRIBUTE" xmlName="name" formatString=""/>
        <ModelProperty propertyName="isActive" dataType="BOOLEAN" xmlType="ATTRIBUTE" xmlName="isActive" formatString=""/>
        <ModelProperty propertyName="compensation" dataType="NUMBER" xmlType="ELEMENT" xmlName="Compensation" formatString=""/>
        <ModelProperty propertyName="compensationTerm" dataType="ENUM" xmlType="ELEMENT" xmlName="CompensationTerm" formatString=""/>
    </ModelClass>
	
	<ModelArray xmlName="Employees">
        <ModelArrayElement dataType="UDC" xmlName="Employee" formatString=""/>
	</ModelArray>

	<ModelDictionary xmlName="Computers">
        <ModelDictionaryElement key="Computer 1" dataType="STRING" xmlName="Computer1" formatString=""/>
        <ModelDictionaryElement key="Computer 2" dataType="STRING" xmlName="Computer2" formatString=""/>
        <ModelDictionaryElement key="Computer 3" dataType="STRING" xmlName="Computer3" formatString=""/>
	</ModelDictionary>
	
</Model>
